# Generated by Django 3.0.7 on 2020-07-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='picture',
            field=models.ImageField(upload_to='commerce/media/listing_pics'),
        ),
    ]
